title: R Rautenbach
logo: /img/headshot_circle.png
show_downloads: False
theme: jekyll-theme-minimal

description: A seasoned attorney with over a decade's experience, now a Bachelor of Science in Computing graduate from the University of South Africa. This portfolio showcases my transition to technology, blending legal expertise with computing skills for innovation in tech.



