title: R Rautenbach
logo: /img/headshot.jpg
show_downloads: False
theme: jekyll-theme-minimal

description: **About Me
I am a seasoned attorney with over 10 years of experience in legal practice, specializing in [mention your areas of expertise, if any]. Recently, I embarked on a new journey to explore my passion for technology and computing. In May 2024, I obtained my Bachelor of Science in Computing from the University of South Africa, diving deep into the world of software development, data analysis, and computer systems.

This portfolio showcases my transition from law to technology, featuring projects that demonstrate my skills and knowledge acquired during my academic journey and beyond. From legal tech innovations to programming projects, I am dedicated to leveraging my diverse background to create impactful solutions and contribute to the ever-evolving tech industry.

Feel free to explore my projects and reach out to discuss collaborations or opportunities! 



