title: R Rautenbach
logo: /img/headshot_circle.png
show_downloads: False
theme: jekyll-theme-minimal

description: As an attorney with over a decade of experience, I recently pivoted to technology after completing my Bachelor of Science in Computing from the University of South Africa. This portfolio reflects my journey, highlighting projects that fuse legal insight with newfound computing proficiency to innovate within the tech realm.



