title: R Rautenbach
logo: /img/headshot_circle.png
show_downloads: False
theme: jekyll-theme-minimal

description: I'm an attorney with over 10 years of experience, but my recent Bachelor of Science in Computing from the University of South Africa marks a new chapter. This portfolio showcases my transition to technology, featuring some projects that blend legal expertise with newfound computing skills, aiming to innovate and contribute to the evolving tech landscape.



