title: R Rautenbach
logo: /img/headshot.jpg
show_downloads: False
theme: jekyll-theme-minimal

description: test what goes here 
link: https://ru5hx.github.io/portfolio/#work-experience
steps:
  - title: Add a profile link
    description: Learn how to create links in Markdown.
    link:  https://ru5hx.github.io/portfolio/#work-experience 
#link: https://ru5hx.github.io/portfolio/#work-experience
#link: https://github.com/ru5hX/portfolio/blob/main/README.md#work-experience
#- title: Work Experience
#  link: https://ru5hx.github.io/portfolio/#work-experience


